import { useState } from 'react'
import { Link,useNavigate } from 'react-router'
import { useStore } from '../StoreContext'
import { useDemo } from '../../admin/DemoContext'
import { Field } from '../../admin/components/AdminUI'
import { primaryClass,inputClass } from '../../admin/components/styles'
import { calculateTotals,money } from '../../../lib/documents'
export default function CheckoutPage(){const store=useStore(),{settings,setInvoices,setOrders}=useDemo(),navigate=useNavigate(),[method,setMethod]=useState('Delivery'),[error,setError]=useState('');const lines=store.items.map(i=>({id:i.id,name:i.product?.name||'',price:i.product?.price||0,quantity:i.quantity})),totals=calculateTotals(lines,settings.tax);
 function submit(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(store.items.some(i=>!i.product||i.quantity>i.product.stock)){setError('Some items are no longer available in that quantity. Update your cart.');return}if(!data.name.trim()||!data.phone.trim()||(method==='Delivery'&&!data.address.trim())){setError('Complete the contact and delivery details.');return}const id='INV-'+crypto.randomUUID().slice(0,8).toUpperCase(),date=new Date().toISOString().slice(0,10);const invoice={id,customer:data.name.trim(),date,due:date,currency:settings.currency,lines,items:lines.reduce((n,l)=>n+l.quantity,0),amount:totals.total,taxRate:settings.tax,status:'Pending',notes:'Storefront demo order; no payment collected.'};setInvoices(current=>[invoice,...current]);setOrders(current=>({...current,[id]:{method,location:method==='Delivery'?data.address.trim():'',fee:0,deliveryFeePending:method==='Delivery',rider:'',requestedPaymentMethod:data.payment,contact:{email:data.email,phone:data.phone},status:'Packing'}}));store.setHistory(current=>[{...invoice,fulfillment:method},...current]);store.setProfile({name:data.name,email:data.email,phone:data.phone,address:data.address||''});store.clear();store.setNotice('Demo order '+id+' created. No purchase or payment has been processed.');navigate('/profile')}
 if(!store.items.length)return <p>Your cart is empty. <Link className="text-accent" to="/shop">Go shopping</Link></p>;
 return <><h1 className="mb-3 text-3xl font-bold">Checkout</h1><p className="mb-8 text-sm text-muted">Frontend preview: this creates a demo order only. No money is collected or stock reserved.</p><form onSubmit={submit} className="grid items-start gap-7 lg:grid-cols-[2fr_1fr]"><section className="space-y-5 rounded-xl border border-outline bg-surface p-6"><h2 className="text-xl font-semibold">Contact details</h2>{[['Full name','name','text'],['Email','email','email'],['Phone','phone','tel']].map(([label,name,type])=><Field key={name} label={label}><input className={inputClass} name={name} type={type} required defaultValue={store.profile[name]}/></Field>)}<Field label="How would you like to receive your order?"><select className={inputClass} value={method} onChange={e=>setMethod(e.target.value)}><option>Delivery</option><option>Pickup</option></select></Field>{method==='Delivery'?<Field label="Delivery address"><textarea className={inputClass} name="address" required defaultValue={store.profile.address}/></Field>:<p className="text-sm text-muted">Pickup: {settings.address}, {settings.city}</p>}<Field label="Preferred payment method"><select className={inputClass} name="payment"><option>Cash</option><option>Transfer</option></select></Field><p className="text-xs text-muted">Our team will confirm payment instructions and delivery costs when live ordering is available.</p></section><aside className="space-y-4 rounded-xl border border-outline bg-surface p-6"><h2 className="text-xl font-bold">Your order</h2>{lines.map(l=><p key={l.id} className="flex justify-between gap-3 text-sm"><span>{l.name} ? {l.quantity}</span><span>{money(l.price*l.quantity,settings.currency)}</span></p>)}<hr className="border-outline"/><p className="flex justify-between"><span>Subtotal</span><span>{money(totals.subtotal,settings.currency)}</span></p><p className="flex justify-between"><span>Tax ({settings.tax}%)</span><span>{money(totals.tax,settings.currency)}</span></p><p className="text-sm text-muted">{method==='Delivery'?'Delivery: to be confirmed, excluded below':'Pickup: no delivery fee'}</p><p className="flex justify-between font-bold"><span>Total</span><span>{money(totals.total,settings.currency)}</span></p>{error&&<p role="alert" className="text-red-500">{error}</p>}<button className={primaryClass+' w-full'}>Place demo order</button></aside></form></>}
