import { Link } from 'react-router'
import { useInventory } from '../../inventory/InventoryContext'
import { useDemo } from '../../admin/DemoContext'
import { useStore } from '../StoreContext'
import ProductCard from '../components/ProductCard'
export function StoreCategories(){const {categories,products}=useInventory();return <><h1 className="mb-8 text-3xl font-bold">Shop by category</h1><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{categories.map(c=><Link key={c} to={'/categories/'+encodeURIComponent(c)} className="rounded-2xl border border-outline bg-surface p-8 hover:border-accent"><h2 className="text-xl font-semibold">{c}</h2><p className="mt-3 text-sm text-muted">{products.filter(p=>p.category===c).length} products</p><p className="mt-6 text-sm text-accent">Explore collection ?</p></Link>)}</div>{!categories.length&&<p>New collections are on the way.</p>}</>}
export function WishlistPage(){const {wishlist,wishlistLoading,wishlistError}=useStore(),{products,loading,error}=useInventory();if(loading||wishlistLoading)return <p>Loading your wishlist...</p>;if(error||wishlistError)return <p>Your saved wishlist could not be loaded. Please retry loading products above.</p>;const rows=products.filter(p=>wishlist.includes(p.id));return <><h1 className="mb-8 text-3xl font-bold">Your wishlist</h1><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{rows.map(p=><ProductCard key={p.id} product={p}/>)}</div>{wishlist.length>rows.length&&<p className="mt-5 text-muted">Some saved products are currently unavailable. They remain in your wishlist.</p>}{!wishlist.length&&<p>No saved products yet. <Link className="text-accent" to="/shop">Explore the shop</Link></p>}</>}
export function ContactPage(){const {settings}=useDemo();return <section className="mx-auto max-w-2xl rounded-2xl border border-outline bg-surface p-8"><h1 className="text-3xl font-bold">Let?s talk</h1><p className="my-5 text-muted">Questions about a product, delivery, pickup, or returns? Get in touch with our team.</p><div className="space-y-4"><a className="block text-accent" href={'tel:'+settings.phone}>{settings.phone}</a><a className="block break-all text-accent" href={'mailto:'+settings.email}>{settings.email}</a><p>{settings.address}<br/>{settings.city}</p></div></section>}
export function StoreNotFound(){return <div className="py-20 text-center"><h1 className="mb-4 text-3xl font-bold">Page not found</h1><Link to="/shop" className="text-accent">Return to the shop</Link></div>}
