import { useState } from 'react'
import { useDemo } from '../../admin/DemoContext'
import { Field } from '../../admin/components/AdminUI'
import { primaryClass, inputClass } from '../../admin/components/styles'
import { money } from '../../../lib/documents'
export default function ManualPayments({invoice}) {
 const {orders,setOrders}=useDemo(),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const records=orders[invoice.id]?.payments||[]
 async function save(e){e.preventDefault();const form=e.currentTarget,data=new FormData(form),amount=Number(data.get('amount')),file=data.get('evidence');if(!Number.isFinite(amount)||amount<=0){setNotice('Enter a positive amount.');return}if(file?.size&&(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)||file.size>10*1024*1024)){setNotice('Use a JPG, PNG, WebP or PDF up to 10 MB.');return}
 setBusy(true);setNotice('');try{let evidence=null;if(file?.size){const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});evidence={url,name:file.name,type:file.type}}const payment={id:crypto.randomUUID(),method:data.get('method'),amount,evidence,date:new Date().toISOString()};setOrders(current=>({...current,[invoice.id]:{...current[invoice.id],payments:[...(current[invoice.id]?.payments||[]),payment]}}));form.reset();setNotice('Payment recorded locally; awaiting verification.')}catch{setNotice('Could not read the evidence. Please try again.')}finally{setBusy(false)}}
 return <section className="space-y-4"><h3 className="font-semibold">Record cash / transfer payment</h3><form onSubmit={save} className="space-y-4"><Field label="Payment method"><select name="method" className={inputClass}><option>Cash</option><option>Transfer</option></select></Field><Field label={'Amount paid ('+(invoice.currency||'USD')+')'}><input className={inputClass} type="number" name="amount" min="0.01" step="0.01" required/></Field><Field label="Payment evidence (image or PDF)"><input type="file" name="evidence" accept="image/jpeg,image/png,image/webp,application/pdf" className={inputClass}/></Field><button disabled={busy} className={primaryClass}>{busy?'Saving...':'Record payment'}</button></form>{notice&&<p role="status" className="text-sm text-muted">{notice}</p>}<p className="text-sm">Recorded payments: {money(records.reduce((sum,p)=>sum+p.amount,0),invoice.currency)}</p><p className="text-xs text-muted">Records and evidence are temporary. Recording a payment does not verify a transfer or change backend payment status.</p><div className="space-y-3">{records.map(p=><article className="rounded-lg border border-outline p-3" key={p.id}><p className="font-medium">{p.method} ? {money(p.amount,invoice.currency)}</p><p className="text-xs text-muted">{new Date(p.date).toLocaleString()} ? Unverified</p>{p.evidence&&<><a className="mt-2 block text-sm text-accent" href={p.evidence.url} download={p.evidence.name}>Download evidence: {p.evidence.name}</a>{p.evidence.type.startsWith('image/')&&<img src={p.evidence.url} alt="Payment evidence" className="mt-2 max-h-48 w-full object-contain"/>}</>}</article>)}</div></section>
}
