import { useState } from 'react'
import Modal from '../../../components/Modal'
import { Field } from '../../admin/components/AdminUI'
import { inputClass, primaryClass, secondaryClass } from '../../admin/components/styles'
export default function PersonDialog({kind,entry,mode,onClose,onSave,onDelete}) {
 const user=kind==='user',view=mode==='view', [error,setError]=useState('')
 function save(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));delete data.password;for(const key of ['name','email',...(!user?['phone']:[])])if(!data[key].trim()){setError('Please complete the required fields.');return}const failure=onSave({...entry,...data,name:data.name.trim(),email:data.email.trim()});if(failure)setError(failure)}
 return <Modal title={mode==='delete'?'Delete '+kind+'?':view?'Customer Details':(entry?'Edit ':'Add New ')+(user?'User':'Customer')} onClose={onClose}>{mode==='delete'?<><p>Remove {entry.name} from this demo workspace?</p><div className="mt-5 flex gap-3"><button className={primaryClass} onClick={()=>onDelete(entry.id)}>Delete</button><button className={secondaryClass} onClick={onClose}>Cancel</button></div></>:<form className="grid gap-4" onSubmit={save}>
 <Field label={(user?'Full':'Customer')+' Name *'}><input className={inputClass} name="name" defaultValue={entry?.name} placeholder="Enter full name" required readOnly={view}/></Field>
 <Field label="Email *"><input className={inputClass} name="email" type="email" defaultValue={entry?.email} placeholder="name@email.com" required readOnly={view}/></Field>
 {user?<><Field label="Phone"><input className={inputClass} name="phone" type="tel" defaultValue={entry?.phone||''} placeholder="Contact number"/></Field><Field label="Role *"><select className={inputClass} name="role" defaultValue={entry?.role||'Staff'}>{['Admin','Manager','Staff','Delivery Rider'].map(r=><option key={r}>{r}</option>)}</select></Field>{!entry&&<Field label="Password *"><input className={inputClass} name="password" type="password" autoComplete="new-password" minLength={8} required placeholder="At least 8 characters"/><span className="text-xs font-normal text-muted">Demo only: this password is discarded; no login account is created.</span></Field>}</>:<>{[['Phone *','phone','tel'],['Address','address','text'],['City','city','text']].map(([label,name,type])=><Field key={name} label={label}><input className={inputClass} name={name} type={type} defaultValue={entry?.[name]} required={name==='phone'} readOnly={view}/></Field>)}</>}
 {entry&&<Field label="Status"><select className={inputClass} name="status" defaultValue={entry.status} disabled={view}><option>Active</option><option>Inactive</option></select></Field>}
 {error&&<p role="alert" className="text-sm text-red-500">{error}</p>}
 <div className="mt-2 flex gap-3">{!view&&<button className={primaryClass}>{entry?'Save Changes':'Add '+(user?'User':'Customer')}</button>}<button type="button" className={secondaryClass} onClick={onClose}>{view?'Close':'Cancel'}</button></div></form>}</Modal>
}
