import { useState } from 'react'
import { Building, DollarSign, Bell, Shield, Save } from 'lucide-react'
import { PageHeading, Field } from '../../admin/components/AdminUI'
import { inputClass, primaryClass } from '../../admin/components/styles'
import { useDemo } from '../../admin/DemoContext'
import Modal from '../../../components/Modal'
function Section({title,icon:Icon,children}){return <section className="rounded-xl border border-outline p-6"><h2 className="mb-6 flex items-center gap-3 text-xl font-semibold"><span className="rounded-lg bg-accent/10 p-2 text-accent"><Icon size={22}/></span>{title}</h2>{children}</section>}
export default function SettingsPage(){const {settings,setSettings}=useDemo(),[notice,setNotice]=useState(''),[security,setSecurity]=useState('')
 async function save(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{await setSettings({...data,tax:Number(data.tax),emailNotifications:data.emailNotifications==='on',stockAlerts:data.stockAlerts==='on',invoiceReminders:data.invoiceReminders==='on'});setNotice('Settings saved. Notification delivery is not available yet.')}catch(e){setNotice(e.message)}}
 return <><PageHeading title="Settings" subtitle="Manage your system preferences and configuration"/><form className="space-y-6" onSubmit={save}><Section title="Company Information" icon={Building}><div className="grid gap-5 md:grid-cols-2">{[['Company Name','name'],['Email','email'],['Phone','phone'],['Address','address'],['City','city']].map(([label,name])=><div key={name} className={name==='name'||name==='address'?'md:col-span-2':''}><Field label={label}><input className={inputClass} name={name} type={name==='email'?'email':'text'} defaultValue={settings[name]} required={name==='name'}/></Field></div>)}</div></Section><Section title="Financial Settings" icon={DollarSign}><div className="grid gap-5 md:grid-cols-2"><Field label="Currency"><select className={inputClass} name="currency" defaultValue={settings.currency}>{['USD','NGN','GBP','EUR'].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Default Tax Rate (%)"><input className={inputClass} name="tax" type="number" min="0" max="100" step="0.01" defaultValue={settings.tax} required/></Field></div></Section><Section title="Notifications" icon={Bell}><div className="space-y-4">{[['Email Notifications','Receive email updates about system activities','emailNotifications'],['Low Stock Alerts','Get notified when products are running low','stockAlerts'],['Invoice Reminders','Send reminders for unpaid invoices','invoiceReminders']].map(([label,description,name])=><label key={name} className="flex items-center justify-between gap-4 rounded-lg bg-background p-4"><span><span className="font-medium">{label}</span><span className="mt-1 block text-sm text-muted">{description}</span></span><input disabled type="checkbox" role="switch" name={name} defaultChecked={settings[name]} className="size-5 accent-accent"/></label>)}</div></Section><Section title="Security" icon={Shield}><div className="space-y-4">{[['Change Password','Update your account password'],['Two-Factor Authentication','Add an extra layer of security'],['Session Management','View and manage active sessions']].map(([name,description])=><button key={name} type="button" onClick={()=>setSecurity(name)} className="block w-full rounded-lg border border-outline bg-background p-4 text-left hover:border-accent"><span className="font-medium">{name}</span><span className="mt-1 block text-sm text-muted">{description}</span></button>)}</div></Section>{notice&&<p role="status" className="text-sm text-muted">{notice}</p>}<div className="flex justify-end"><button className={primaryClass}><Save size={18}/>Save Changes</button></div></form>{security&&<Modal title={security} onClose={()=>setSecurity('')}><p className="text-muted">This control requires a connected authentication service. No account security settings have been changed.</p></Modal>}</>
}
