import { DollarSign, ShoppingCart, ChartColumn, TrendingUp } from 'lucide-react'
import { PageHeading } from '../../admin/components/AdminUI'
import { tableClass } from '../../admin/components/styles'
import { useDemo } from '../../admin/DemoContext'
import StatusBadge from '../../../components/StatusBadge'
import { money } from '../../../lib/documents'
const months=[['Jan',45231],['Dec',36784],['Nov',42150],['Oct',38920],['Sep',41200],['Aug',39500]]
const top=[['Office Chair Premium',145,43485.55,32],['Monitor 27 inch 4K',87,39149.13,28],['Laptop Stand Pro',234,21057.66,15],['Wireless Mouse X',412,12355.88,22],['Desk Organizer Set',189,4718.11,8]]
export default function SalesReportsPage(){const {invoices}=useDemo();return <><PageHeading title="Sales Reports" subtitle="Analyze your sales performance and trends"/><p className="mb-5 text-xs text-muted">Historical demo snapshot: January 2026, USD. Recent sales below use paid invoices in this workspace.</p><div className="mb-6 grid gap-4 md:grid-cols-3">{[['This Month Revenue','$45,231',23,DollarSign],['Orders This Month','156',23,ShoppingCart],['Year-to-Date Revenue','$487,320',18,ChartColumn]].map(([label,value,growth,Icon])=><div key={label} className="rounded-xl border border-outline p-6"><div className="mb-5 flex items-center justify-between"><span className="rounded-lg bg-accent/10 p-3 text-accent"><Icon/></span><span className="flex gap-1 text-sm text-emerald-600"><TrendingUp size={16}/>+{growth}%</span></div><p className="text-sm text-muted">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div>)}</div><div className="grid gap-6 xl:grid-cols-3"><section className="rounded-xl border border-outline p-6 xl:col-span-2"><h2 className="mb-7 text-xl font-bold">Monthly Revenue Trend</h2><div className="space-y-6">{months.map(([month,value])=><div key={month}><div className="mb-2 flex justify-between text-sm"><span className="text-muted">{month}</span><span>{money(value)}</span></div><div className="h-3 rounded-full bg-avatar" role="meter" aria-label={month+' revenue in USD'} aria-valuemin={0} aria-valuemax={50000} aria-valuenow={value}><div className="h-full rounded-full bg-linear-to-r from-accent to-purple-400" style={{width:value/500+'%'}}/></div></div>)}</div></section><section className="rounded-xl border border-outline p-6"><h2 className="mb-6 text-xl font-bold">Top Products</h2><div className="space-y-4">{top.map(([name,sales,total,growth])=><div key={name} className="rounded-lg bg-background p-4"><div className="flex justify-between gap-3 text-sm"><strong>{name}</strong><span className="text-emerald-600">+{growth}%</span></div><div className="mt-3 flex justify-between text-xs"><span className="text-muted">{sales} sales</span><span>{money(total)}</span></div></div>)}</div></section></div><section className="mt-6 overflow-auto rounded-xl border border-outline"><h2 className="p-6 text-xl font-bold">Recent Sales</h2><table className={tableClass}><thead><tr>{['Invoice','Customer','Date','Amount','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{invoices.filter(i=>i.status==='Paid').map(i=><tr key={i.id}><td className="text-accent">{i.id}</td><td>{i.customer}</td><td className="text-muted">{i.date}</td><td>{money(i.amount,i.currency)}</td><td><StatusBadge status="Completed"/></td></tr>)}</tbody></table></section></>}
