import { useState } from 'react'
import { useDemo } from '../../admin/DemoContext'
import { useInventory } from '../../inventory/InventoryContext'
import { Field } from '../../admin/components/AdminUI'
import { inputClass, primaryClass, secondaryClass, tableClass } from '../../admin/components/styles'
import LineItems from './LineItems'
import { calculateTotals, money } from '../../../lib/documents'
import Modal from '../../../components/Modal'
import InvoicePreview from '../../invoices/components/InvoicePreview'
export default function DocumentView({ document, kind = 'invoice', onSave, onConvert }) {
 const {settings}=useDemo(),{products}=useInventory()
 const [editing,setEditing]=useState(false),[preview,setPreview]=useState(false),[notice,setNotice]=useState('')
 const [lines,setLines]=useState(document.lines?.length?document.lines:[{id:'summary',name:'Item breakdown unavailable ? replace with actual items',quantity:1,price:document.amount}])
 const [rate,setRate]=useState(document.taxRate||0)
 const title=kind==='quotation'?'Quotation':'Invoice'
 const totals=calculateTotals(lines,rate)
 function save(e){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));if(!values.customer.trim()||lines.some(l=>!l.name.trim()))return;const updated={...document,...values,customer:values.customer.trim(),lines:lines.map(l=>({...l,quantity:Number(l.quantity),price:Number(l.price)})),taxRate:Number(rate),items:lines.reduce((n,l)=>n+Number(l.quantity),0),amount:totals.total};onSave(updated);setEditing(false);setNotice(title + ' saved.')}
 return <div className="space-y-5">
 <div className="flex flex-wrap gap-3">{onSave&&!editing&&<button className={primaryClass} onClick={()=>{setLines(document.lines?.length?document.lines:[{id:'summary',name:'Invoice summary',quantity:1,price:document.amount}]);setRate(document.taxRate||0);setEditing(true)}}>Edit {kind}</button>}{!editing&&<button className={secondaryClass} onClick={()=>setPreview(true)}>Download {title} PDF</button>}{onConvert&&!editing&&<button className={secondaryClass} onClick={()=>{const result=onConvert(document);setNotice(result)}}>Convert to invoice</button>}</div>
 {editing?<form onSubmit={save} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Customer"><input className={inputClass} name="customer" defaultValue={document.customer} required/></Field><Field label={kind==='quotation'?'Valid until':'Due date'}><input className={inputClass} type="date" name="due" defaultValue={document.due||''} required/></Field><Field label="Tax (%)"><input className={inputClass} type="number" min="0" max="100" step="0.01" value={rate} onChange={e=>setRate(e.target.value)} required/></Field><Field label="Status"><select disabled={kind==='invoice'} className={inputClass} name="status" defaultValue={document.status}>{(kind==='quotation'?['Pending','Accepted','Rejected','Expired']:[document.status]).map(s=><option key={s}>{s}</option>)}</select></Field></div><LineItems lines={lines} setLines={setLines} products={products} currency={document.currency||'USD'}/><p className="text-right font-bold">Total: {money(totals.total,document.currency)}</p><Field label="Notes"><textarea className={inputClass} name="notes" defaultValue={document.notes||''}/></Field><button className={primaryClass}>Save changes</button><button type="button" className={secondaryClass+' ml-3'} onClick={()=>setEditing(false)}>Cancel</button></form>:<div className="rounded-xl border border-outline p-5"><div className="flex flex-wrap justify-between gap-6"><div><h2 className="text-xl font-bold">{settings.name}</h2><p className="mt-3 text-sm text-muted">{settings.address}<br/>{settings.city}<br/>{settings.phone}<br/>{settings.email}</p></div><div className="sm:text-right"><h2 className="text-2xl font-bold uppercase">{title}</h2><p>{document.id}</p><p className="text-sm text-muted">Issued: {document.date}</p><p className="text-sm text-muted">{kind==='quotation'?'Valid until':'Due'}: {document.due||'Not specified'}</p></div></div><div className="my-6"><p className="font-semibold">Customer: {document.customer}</p><p className="text-sm text-muted">Status: {document.status}</p></div><div className="overflow-auto"><table className={tableClass}><thead><tr>{['Item','Quantity','Rate','Amount'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{(document.lines?.length?document.lines:[{id:'summary',name:'Summary (item breakdown unavailable)',quantity:1,price:document.amount}]).map(l=><tr key={l.id}><td>{l.name}</td><td>{l.quantity}</td><td>{money(l.price,document.currency)}</td><td>{money(Math.round(l.price*100)*l.quantity/100,document.currency)}</td></tr>)}</tbody></table></div><div className="mt-5 space-y-2 text-right"><p>Tax rate: {document.taxRate||0}%</p><p className="text-xl font-bold">Total: {money(document.amount,document.currency)}</p></div><p className="mt-5 whitespace-pre-wrap text-sm text-muted">{document.notes}</p></div>}
 {notice&&<p role="status" className="text-sm text-muted">{notice}</p>}
 {preview&&<Modal wide title={title+' PDF preview'} onClose={()=>setPreview(false)}><InvoicePreview invoice={document} business={settings} kind={kind}/></Modal>}
 </div>
}
